# https://aka.ms/yaml

jobs:

- job: runtime
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script:
      cmake -E make_directory cmake-build
    displayName: 'Creating build directory'
  - script:
      wget -O $(Agent.TempDirectory)/libc++abi.deb
      http://apt.llvm.org/trusty/pool/main/l/llvm-toolchain-8/libc++abi1-8_8.0.1~svn360950-1~exp1~20190517011409.67_amd64.deb
    displayName: 'Downloading libc++abi'
  - script:
      wget -O $(Agent.TempDirectory)/libc++.deb
      http://apt.llvm.org/trusty/pool/main/l/llvm-toolchain-8/libc++1-8_8.0.1~svn360950-1~exp1~20190517011409.67_amd64.deb
    displayName: 'Downloading libc++'
  - script:
      sudo dpkg -i $(Agent.TempDirectory)/libc++abi.deb $(Agent.TempDirectory)/libc++.deb
    displayName: 'Installing libc++'
  - script:
      sudo apt install ninja-build texinfo autopoint -y
    displayName: 'Installing dependencies'
  - script:
      cmake -E chdir cmake-build
      cmake ..
      -GNinja
      -DCMAKE_TOOLCHAIN_FILE=../cmake/MeToolchain.cmake
      -DWIMAL_TARGET=x64-linux
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX="$(Build.BinariesDirectory)/$(Agent.JobName)"
    displayName: 'Configuring'
  - script:
      cmake -E env VERBOSE=1 ALL=1 cmake --build cmake-build --target strip-all --
    displayName: 'Building'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/$(Agent.JobName)'
      includeRootFolder: true
      archiveType: 'tar'
      tarCompression: 'xz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Agent.JobName)-$(Build.BuildNumber).tar.xz'
      replaceExistingArchive: true
    displayName: 'Creating tarball'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(Agent.JobName)-$(Build.BuildNumber)'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Uploading'
